"""add email_fichas to ligas

Revision ID: 7b46c8ad51db
Revises: 8dae8f33912f
Create Date: 2026-01-05 10:06:04.012370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b46c8ad51db'
down_revision: Union[str, None] = '8dae8f33912f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ligas', sa.Column('email_fichas', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ligas', 'email_fichas')
    # ### end Alembic commands ###
