"""Add nextcloud fields to user (non-destructive)

Revision ID: db8144756603
Revises: 72a20bb2d4f9
Create Date: 2026-02-03 16:54:50.651406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'db8144756603'
down_revision: Union[str, None] = '72a20bb2d4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE:
    # This migration is intentionally limited to additive changes on `users`.
    # A previous autogenerated draft included destructive operations
    # (dropping tables/indexes unrelated to Nextcloud) that could cause data loss.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = {column["name"] for column in inspector.get_columns("users")}

    if "nextcloud_url" not in existing_columns:
        op.add_column("users", sa.Column("nextcloud_url", sa.String(length=255), nullable=True))
    if "nextcloud_user" not in existing_columns:
        op.add_column("users", sa.Column("nextcloud_user", sa.String(length=100), nullable=True))
    if "nextcloud_password_enc" not in existing_columns:
        op.add_column("users", sa.Column("nextcloud_password_enc", sa.String(length=500), nullable=True))


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = {column["name"] for column in inspector.get_columns("users")}

    if "nextcloud_password_enc" in existing_columns:
        op.drop_column("users", "nextcloud_password_enc")
    if "nextcloud_user" in existing_columns:
        op.drop_column("users", "nextcloud_user")
    if "nextcloud_url" in existing_columns:
        op.drop_column("users", "nextcloud_url")
